version: "3"
services:
  my-web-app-db:
    image: postgres
    environment:
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_DATABASE=myPostgresDB
  my-web-app:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - my-web-app-db


